print("Quadratic Equation Solver v1.0")
print("Equation: ax^2+bx+c=0")
a = strtoi(readline(prompt="Enter 'a': "))
b = strtoi(readline(prompt="Enter 'b': "))
c = strtoi(readline(prompt="Enter 'c': "))
x1 = (-b+sqrt(b^2-4*a*c))/(2*a)
x2 = (-b-sqrt(b^2-4*a*c))/(2*a)
print(paste("x1", "=", toString(x1)))
print(paste("x2", "=", toString(x2)))